#!/bin/bash

#change to the directory of the script
cd $(dirname "$0")

#temp: don't use rlwrap bc I can't figure out how to install on lightsail instance LOL
../../arc.sh -n -i ../appcmd.arc "app-start" "news"
